import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { PantheonClientProvider } from "~/app/_components/pantheon-provider";

export const metadata: Metadata = {
  title: "Your Flight Tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <PantheonClientProvider>{children}</PantheonClientProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
